### ISSUE TITLE
N32G4FR arm-gcc startup files are configured, but it's not work

### ISSUE THREAD

**Issue by rx-ted** [github0null/eide-templates#20]
N32G4FR
arm-gcc 
startup files was changed to gcc
they are configured, but not work.
I compile and download *.bin to N32G4FR board. But it's not work.
my project path is [https://github.com/rx-ted/led_blink.git](led_blink)
Help me see if my project configuration is correct.
Thanks.

**Comment by github0null** [comment]
Use Cortex-debug to debug your code

**Comment by rx-ted** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by rx-ted** [comment]
I deliberately debug and run other development boards successfully, but this N32G4FR development board can not run, debugging can not find the problem, I do not know the reason. Thanks.

**Comment by Persama** [comment]
@rx-ted N32G4FR模板GCC环境的错误已修复，更新为V1.1版本

**Comment by rx-ted** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
