### ISSUE TITLE
CH582模版中大小写不一致导致在linux下编译链接不通过

### ISSUE THREAD

**Issue by yuqiancn** [github0null/eide-templates#38]
找不到“CH58xBLE_LIB.H”，需要把LIB/的CH58xBLE_LIB.h的扩展名大写；ld找不到“CH58xBLE”，需要把LIB/的LIBCH58xBLE.a改为libCH58xBLE.a。其余头文件及库可能也有类似问题

**Comment by github0null** [comment]
帮你@一下原作者 @zerosensei

当然你也可以帮忙修改一下，pull-request 到该仓库

**Comment by zerosensei** [comment]
@yuqiancn 我已修改，但是我这里没有EIDE运行的Linux环境，如果可以的话你可以试一下。
