### ISSUE TITLE
STM32F103C8 CubeMX 模板无法导入

### ISSUE THREAD

**Issue by summerBreeze03** [github0null/eide-templates#44]
项目截图
![屏幕截图_20241029_000503](https://github.com/user-attachments/assets/4872af9d-2fbf-4001-939e-d6fb7d1cb937)
报错信息
![屏幕截图_20241029_000246](https://github.com/user-attachments/assets/512fc505-9689-48ef-bef7-32c50c4d6eb1)
同时项目的 Makefile 写错了一行导致无法执行，删了即可
![屏幕截图_20241029_000709](https://github.com/user-attachments/assets/259d8237-5f34-4cc1-af56-d3916b49dc59)

**Comment by github0null** [comment]
@summerBreeze03 

这个模板可能过于老旧了，打开 eide.json, 在开头添加版本号:

```
"version": "2.0",
```

![image](https://github.com/user-attachments/assets/679805d2-c061-4d0d-bd4c-4f0464dc37cc)

之后重启工作区。右下角会弹出提示升级项目，点击确认

**Comment by github0null** [comment]
这个已经修复
